language: python
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy-5.4.1
script:
# Coverage slows this old pypy down to several minutes
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then zope-testrunner --test-path=src; fi
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run -m zope.testrunner --test-path=src; fi

after_success:
  - coveralls
notifications:
  email: false

install:
  - pip install -U pip setuptools
  - pip install -U coveralls coverage
  - pip install -U -e ".[test]"


cache: pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
