language: python
dist: xenial
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy2.7-6.0
matrix:
  include:
    - python: 3.7
      name: "Flake8"
      install:  pip install -U flake8
      script: flake8 --doctests src setup.py
      after_success:
script:
  - COVERAGE_PROCESS_START=.coveragerc coverage run -m zope.testrunner --test-path=src -vv

after_success:
  - coverage combine
  - coveralls
notifications:
  email: false

install:
  - pip install -U pip setuptools
  - pip install -U coveralls coverage
  - pip install -U -e ".[test]"


cache: pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
